### ISSUE TITLE
RGDN gray checkpoint

### ISSUE THREAD

**Issue by ronsoohyeong** [OlgaChaganova/non-blind-deconvolution-benchmark#2]
Hi,
RGDN checkpoint at https://github.com/donggong1/learn-optimizer-rgdn has 3 channels, while the RGDN code here works on 1 channel. 
Can you please let me know how to obtain the grayscale checkpoint RGDN-GRAY-60 ?

Thanks and Regards

**Comment by OlgaChaganova** [comment]
Hi! RGDN-GRAY-60 checkpoint can be found here: https://drive.google.com/drive/folders/1VJAiUclJLwrp4uGoq_sqErfcRMjg1lkc?usp=sharing. But I have to mention these are weights of a model trained by me, and the results are not really good. If you want to use weights from original RGDN repository, you can just specify `in_channels=3` in `RGDNPredictor`.
